### PR TITLE
Updated Manjaro icons

### PR DESCRIPTION
**Pull request by soh-rev**
These commits change the two Manjaro icons to use the newer Manjaro logo.

### CODE REVIEW

**Comment by oberon2007** [comment]
Thank you! Would you like to do another one? :wink: 
https://github.com/oberon2007/plymouth-themes-manjaro/blob/master/manjaro-cinnamon/manjaro-cinnamon.png

**Comment by oberon2007** [comment]
And here: https://github.com/manjaro/manjaro-welcome/blob/master/src/manjaro-welcome.png

**Comment by oberon2007** [comment]
aswell as https://github.com/manjaro/manjaro-welcome/blob/master/src/data/img/logo.png

**Comment by oberon2007** [comment]
and https://github.com/manjaro/manjaro-welcome/blob/master/src/data/img/favicon.png

**Comment by soh-rev** [comment]
Apparently the new logo has different dimensions ([https://github.com/manjaro/manjaro-welcome/pull/30](url)). I didn't notice this when I patched up the ones on your repos.

I'm not sure if you want to roll back these commits on your repos or not. The changes made, even though incorrect, are still closer to the new design than they were before.

Later, I'll look into recreating all the icons with the new dimensions (once I find them). No promises though, my image editing skills are very subpar.

**Comment by oberon2007** [comment]
Don't worry, I missed that, too! :laughing: 
To get the actual new logo you can simply right click the one on the top left of the forum and save it. Voilà now you have a 200x200px template :wink: !
For cinnamon however I will like to keep the maia color and if you could achieve the shiny effect again, that will be lovely.
I think you will basically just have to cut of a bit at the bottom of your fist version, no?

**Pull request merged**
